# Generated by Django 4.0.5 on 2022-06-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
